apiVersion: v1
kind: Service
metadata:
  name: estadisticas-service
  labels:
    app: estadisticas-service
spec:
  type: ClusterIP          # Solo accesible dentro del clúster (no expuesto a Internet)
  selector:
    app: estadisticas-service
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP